INSERT INTO tb_category(name, created_At) VALUES ('Books', NOW())
INSERT INTO tb_category(name, created_At) VALUES ('Electronics', NOW())
INSERT INTO tb_category(name, created_At) VALUES ('Computers', NOW())
INSERT INTO tb_category(name, created_At) VALUES ('Smartphones', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Tablets', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Home Appliances', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Furniture', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Clothing', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Shoes', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Sports', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Toys', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Music', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Movies', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Garden', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Automotive', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Beauty', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Health', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Grocery', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Pet Supplies', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Office Supplies', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Video Games', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Watches', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Jewelry', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Handbags', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Luggage', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Outdoor', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Fitness', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Photography', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Smart Home', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Wearable Tech', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Art', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Crafts', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Industrial', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Construction', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Education', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Security', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Software', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Gaming Accessories', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Streaming Devices', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Networking', NOW());
